# Generated by Django 4.2.10 on 2024-03-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellpaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=150, verbose_name='Брэнд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена'),
        ),
    ]
