# Generated by Django 4.2.10 on 2024-03-18 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellpaper', '0002_product_brand_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.CharField(blank=True, max_length=30, null=True, verbose_name='сообщение')),
                ('carts', models.ManyToManyField(related_name='orders', to='wellpaper.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
